# Generated by Django 5.1.7 on 2025-03-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=20)),
                ("published_date", models.DateField(default=None)),
                ("isbn", models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
